title: Rivka Boord # your name (or website title) here
logo: "/images/Rivka_Boord.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data = power.
  <br><br><br><br>
  Sports. Law. Writing. Mom of two.
  <br><br>
  <a href="https://www.linkedin.com/in/rivkaboord/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
