title: Rivka Boord # your name (or website title) here
logo: <a href="https://ibb.co/nfrr0k3"><img src="https://i.ibb.co/nfrr0k3/Rivka-Boord.jpg" alt="Rivka-Boord" border="0"></a> # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data = power.
  <br><br>
  Sports. Law. Writing. Mom of two.
  <br><br>
  <a href="https://www.linkedin.com/in/rivkaboord/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
